### ISSUE TITLE
Problem with book

### ISSUE THREAD

**Issue by ChristianGiupponi** [FabienSerny/mymodcomments#1]
Hi,
I'm following your book [PrestaShop Module Development](https://www.packtpub.com/web-development/prestashop-module-development) and developing the `mymodcomments` module but there are some problem with the code in the book.

At page 26 you define an html form and at page 29 you try to get the product id with:

`$id_product = Tools::getValue('id_product');`

but in the form there is no field that match this, I have hardcoded it in order to continue with the book

**Comment by ChristianGiupponi** [comment]
Just forget it, the id is automatically get, sorry!

**Comment by FabienSerny** [comment]
Hi,
No problem.
Do not hesitate if you have any questions :)
