### ISSUE TITLE
Chapter 5: Front controllers, Object Models and Overrides (comments.php)

### ISSUE THREAD

**Issue by Stanelis** [FabienSerny/mymodcomments#3]
Hello,

I'm using your tutorial to make my first module. But I get the error in Chapter 5.
```

if ($id_product > 0 && isset($actions_list[$module_action]))    {
            $this->$actions_list[$module_action]()
```

Error message:

> Notice: Array to string conversion in C:\xampp\htdocs\presta\modules\mymodcomments\controllers\front\comments.php on line 19
> 
> Notice: Undefined property: MyModCommentsCommentsModuleFrontController::$Array in C:\xampp\htdocs\presta\modules\mymodcomments\controllers\front\comments.php on line 19
> 
> Fatal error: Uncaught Error: Function name must be a string in C:\xampp\htdocs\presta\modules\mymodcomments\controllers\front\comments.php:19 Stack trace: #0 C:\xampp\htdocs\presta\classes\controller\Controller.php(189): MyModCommentsCommentsModuleFrontController->initContent() #1 C:\xampp\htdocs\presta\classes\Dispatcher.php(367): ControllerCore->run() #2 C:\xampp\htdocs\presta\index.php(28): DispatcherCore->dispatch() #3 {main} thrown in C:\xampp\htdocs\presta\modules\mymodcomments\controllers\front\comments.php on line 19

**Comment by FabienSerny** [comment]
Hi,

What is your PrestaShop version ?
Can you post the zip file of your module here ?

**Comment by Stanelis** [comment]
PrestaShop version 1.6.1.15

I have tried to download your module it haves the same problem. When you try to open all comments from product page.

**Comment by Files90** [comment]
Hei Fabian, I'm studying your module using your book. I have a problem in Search.php override. My $product.mymodcomments variable doesn't exist after uninstalled and re-installed the module. It's like the Search override doesn't work (I checked if in class_index the path is changed, and it is changed in override/classes/Search.php).

**Comment by FabienSerny** [comment]
Hi @Stanelis,
Can you attach the zip file of the module you're testing ?
I was not able to reproduce your issue.

Hi @Files90,
Please open your own thread next time (your question is not relative to the one of @Stanelis)
Add a "die" in the "find" method of your override, and tell me you see it.
Are you sure that your product have comments ?

**Comment by Stanelis** [comment]
The problem was related to PHP version. I accidentally used PHP 7 instead of PHP 5. Everything is good.

**Comment by FabienSerny** [comment]
Ok, good to know :)
