### ISSUE TITLE
Problem with Override

### ISSUE THREAD

**Issue by ghost** [FabienSerny/mymodcomments#4]
Hei Fabien, I'm studying your module using your book. I have a problem in Search.php override. My $product.mymodcomments variable doesn't exist after uninstalled and re-installed the module. It's like the Search override doesn't work (I checked if in class_index the path is changed, and it is changed in override/classes/Search.php).

**Comment by FabienSerny** [comment]
Hi @Files90,

Thanks for opening your own thread :)
Add a "die" in the "find" method of your override, and tell me you see it.
Are you sure that your product have comments ?

Fabien

**Comment by ghost** [comment]
Sorry if I didn't open a new thread!

Actually my override search.php is that (I copy it below). My module is called "mymodcommentsmed". Where I need to put a die() function?! I add it after the "return $find", but it doesn't fix the problem.

`class Search extends SearchCore
{
    public static function find($id_lang, $expr, $page_number = 1, $page_size = 1, $order_by = 'position', $order_way = 'desc', $ajax = false, $use_cookie = true, Context $context = null)
    {
        //Call parent method
        $find = parent::find($id_lang, $expr, $page_number, $page_size, $order_by, $order_way, $ajax, $use_cookie, $context);
        
        //We will check whether $find contains products and whether mymodcommentsmed is installed
        if (isset($find['result']) && !empty($find['result']) && Module::isInstalled('mymodcommentsmed'))
        {
            //List id product
            $products = $find['result'];
            $id_prouct_list = array();

            //Fill the array with the ids of the products found
            foreach ($products as $product)
                $id_prouct_list[] = (int)$product['id_product'];

            //Get grade average and nb comments for product list
            $grades_comments = Db::getInstance()->executeS('
                SELECT `id_product`, AVG(`grade`) as grade_avg,
                count(`id_mymod_comment`) as nb_comments
                FROM `'._DB_PREFIX_.'mymod_comment`
                WHERE `id_product` IN ('.implode(',', $id_product_list).')
                GROUP BY `id_product`
            ');

            //Associate grade and nb comments with product
            foreach ($products as $key => $product)
                foreach ($grades_comments as $grade_comment)
                    if ($grade_comment['id_product'] == $product['id_product'])
                    {
                        $products[$key]['mymodcommentsmed']['grade_avg'] = round($grade_comment['grade_avg']);
                        $products[$key]['mymodcommentsmed']['nb_comments'] = $grade_comment['nb_comments'];
                    }

            $find['result'] = $products;
        }
        
        //Return products
        return $find;
    }

}`

**Comment by FabienSerny** [comment]
Hi,

If you add a die after the "return", it will never be called.
Add a die before the "if" and see if it displays. If not, it means your override is not called, if yes, try to move the die in the "if" section (to see if it enters the condition)

Fabien

**Comment by ghost** [comment]
Mmh, I put the die just before the first "if" and after the $find = parent::find() but it fix nothing. If I use the {debug} in my product-list.tpl page, in the window where I have all the smarty variable, I can see that in the $product variable the 'mymodcommentmed' key is not there.

**Comment by FabienSerny** [comment]
Hi,

The "die" is not meant to fix anything.
The "die" is just here to check if PrestaShop is calling the override, nothing else. If your "die" does not appear on the screen, then it means the override is not called, so the variable "mymodcommentmed" will not be set.

Add a "die('test')" before the parent::find (we never know and try again).
If it still does not display "test", it means that your override is not called.

If it's not called, it's either because your file is not on the right place or your class_index is not regenerated (but since your check this last one, it should not be the issue). You can also try to delete the class_index file and see if it fixes your issue.

**Comment by ghost** [comment]
Sorry for my silly question but I'm newbie in prestashop and I'm trying to understand how create module and how prestashop works. : ]
Okay, I did it but nothing in the screen. 'test' doesn't appear. (I mean in the product-list page, where I have the list of all my products). I tried to remove the class_index.php also, but nothing.

**Comment by FabienSerny** [comment]
No problem :)

Might be a silly question too, but just to be sure, you're on a search page right ?
You're not simply on a category page that list products of the category ?

**Comment by FabienSerny** [comment]
Because product-list is called on both page (Search page and Category listing products page)

**Comment by ghost** [comment]
Okay. Now I am in the right page (Search Page). If I put the die('test'), I have the blank page with the "test" string a top-right, so I think the override is called. BUt, again, I have not access at the variable. Here the code I use in the product-list.tpl file:

`{if isset($product.mymodcommentsmed)}
	<p>
		<b>{l s='Grade:' mod='mymodcommentsmed'}</b> {$product.mymodcommentsmed.grade_avg}/5<br>
		<b>{l s='Number of comments:' mod='mymodcommentsmed'}</b> {$product.mymodcommentsmed.nb_comments}
	</p>
{/if}`

**Comment by FabienSerny** [comment]
Ok, are you sure that the products displayed on your page (when you remove the die) have comments ? If not the variable will not be set.

If the products have comment, put the die in the "if" condition and check if it enters it.
To be sure, change the text of the die such as "die('test2')"

Maybe better things to do, do a 
"d($grades_comments);" just after the SQL request and see what's the result of your request.
If the array displayed is empty, make a die of the SQL request itself and try it directly on your SQL database.
This is just simple php debug methodology, now that you're on the right page, I'm pretty sure you will be able to find the issue :)

Do not hesitate to keep me informed

@+ Fabien

**Comment by ghost** [comment]
Okay, now it's good. I found the error! : ]
Thanks for your help! You can make this issue as Solved!

**Comment by FabienSerny** [comment]
No problem :)
Have a nice day !
