### ISSUE TITLE
Override Product

### ISSUE THREAD

**Issue by servitux** [FabienSerny/mymodcomments#6]
Hi Fabien.

In your override class Product, you use $this->id, but when I try this, the value is null. I've created this small function, similar to yours:

```
<?php

class Product extends ProductCore
{
	public function getCommentsCount()
	{
                 $sql = "SELECT count(id_product) FROM "._DB_PREFIX_."stpc_comments WHERE id_product = ".$this->id;
		$comments = Db::getInstance()->getValue($sql);
		return $comments;
	}
}
```
But $this->id is always null.

What's wrong? 
Thanks.

**Comment by FabienSerny** [comment]
Hi,

Make sure that your object is loaded.
$this->id will be set only if object has been loaded.

new Product();
$this->id will be null

new Product(4)
$this->id will be set to 4 is product exists, otherwise it will be null

**Comment by servitux** [comment]
5 minutes after post this issue, i found the problem than you say.

Sorry for the inconvenience... and thanks for you book.

**Comment by FabienSerny** [comment]
No problem :)
