### ISSUE TITLE
Chapter 5 - comments page does not include overall theme's set up

### ISSUE THREAD

**Issue by BernardA** [FabienSerny/mymodcomments#7]
Hi
I am using Prestashop 1.7.2.4 and I have your Chapter 5 comments working after a few hiccups.

Those hiccups were related to the method in initContent() throwing an error ( already reported in a separate issue) and also the setTemplate method being unable to find the template.

For the first one I adjusted code as follows:

            `		
                if ($id_product > 0 && isset($actions_list[$module_action]))
		{
			$method = $actions_list[$module_action];
			$this->$method();
		}
              `

For the setTemplate, it looks like follows:

`$this->setTemplate('module:mymodcomments/views/templates/front/list.tpl');`

Now, the issue I actually have is that while the comments page shows, it is a completely unstyled page, outside of the theme's setup. 

As you sure understand, one wants to have the same look and feel as per the rest of the website.
I would appreciate if you could show me the way.

Thanks

Bernard

PS:
By the way, as you are certainly aware, the addCSS and addJS methods included in the setMedia method do not work in PS 1.7. I believe they should be added in hooks now.

**Comment by patdec** [comment]
Yes I confirm. I get some errors too. And some are due to PHP 7

### On PHP7

then instead of:

```
if ($id_product > 0 && isset($actions_list[$module_action])) 
{
  $this->$actions_list[$module_action]();
 }
```

I had to write this:

```
if ($id_product > 0 && isset($actions_list[$module_action])) 
{
  $this->{$actions_list[$module_action]}();
}
```
*Note the curly braces.*

### Prestashop 1.7

list.tpl template had to be rewritten:

`<h1>{l s='Comments' mod='mymodcomments'}</h1>`

becomes:
```
{extends file='page.tpl'}

{block name="page_content"}
    <h1>{l s='Comments' mod='mymodcomments'}</h1>
{/block}
```


For adding CSS or JS, I don't. I have to investigate.

**Comment by FabienSerny** [comment]
Hi,

Thanks both for your contribution, I'll make update on the source code as soon as I will have some time.

Meanwhile, do not hesitate to do a PR on branch 1.7 of this repo ^^

Fabien
